client_config_backend: settings
client_config:
  client_id: 623664903149-mv50neqehpkg9t548a3pij8oin0hsos4.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
