client_config_backend: settings
client_config:
  client_id: 88517990399-uik94v200989ffi42ksehp93ouv0hu1q.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
- https://www.googleapis.com/auth/drive.file
