client_config_backend: settings
client_config:
  client_id: 88517990399-o50o8muaa72vtdc1rtave5p8bqqc2ch9.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
- https://www.googleapis.com/auth/drive.file


